services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME : 192.168.18.9
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "dbhistory-sqlserver:1:1"
    depends_on:
      - zookeeper
  debezium:
    image: debezium/connect
    container_name: debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - STATUS_STORAGE_TOPIC=my-connect-statuses
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_REST_ADVERTISED_HOST_NAME=debezium
      - CONNECT_PLUGIN_PATH=/kafka/connect
      - GOOGLE_APPLICATION_CREDENTIALS=/kafka/key/keyfile.json
    volumes:
      - ./conector/debezium-connector-sqlserver-3.0.0.Final.jar:/kafka/connect/debezium-connector-sqlserver-3.0.0.Final.jar
      - ./conector/pubsub-group-kafka-connector-1.3.0.jar:/kafka/connect/pubsub-group-kafka-connector-1.3.0.jar
      - ./keyfile.json:/kafka/key/keyfile.json
    depends_on:
      - kafka